[versions]
convention-plugin = "0.0.2"

java = "21"

spotless = "7.2.1"
palantirJavaFormat = "2.81.0"

spring-boot = "4.0.0"
spring-dependency-management = "1.1.7"

junit = "6.0.1"

[libraries]
swagger-parser = { module = "io.swagger.parser.v3:swagger-parser", version = "2.1.31" }

jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
nullaway = { module = "com.uber.nullaway:nullaway", version = "0.12.10" }
errorprone = { module = "com.google.errorprone:error_prone_core", version = "2.43.0" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
assertj-core = { module = "org.assertj:assertj-core", version = "3.27.6" }

gradle-spring-boot = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
gradle-spring-dependency-management = { module = "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin", version.ref = "spring-dependency-management" }
gradle-errorprone = { module = "net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin", version = "4.3.0" }
gradle-nullaway = { module = "net.ltgt.gradle:gradle-nullaway-plugin", version = "2.3.0" }
gradle-lombok = { module = "io.freefair.lombok:io.freefair.lombok.gradle.plugin", version = "9.0.0" }
gradle-spotless = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version.ref = "spotless" }
gradle-node = { module = "com.github.node-gradle.node:com.github.node-gradle.node.gradle.plugin", version = "7.1.0" }
gradle-openapi-generator = { module = "org.openapi.generator:org.openapi.generator.gradle.plugin", version = "7.17.0"}

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spotless-convention = { id = "io.github.jongminchung.spotless.convention", version.ref = "convention-plugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
